# Default repolinter ruleset for Twitter open source repositories.
#
# This excludes some rules from the default repolinter ruleset because these
# files are inherited from the org-wide .github repository:
#
# - code-of-conduct-file-exists
# - code-of-conduct-file-contains-email
# - security-file-exists
# - github-issue-template-exists
# - github-pull-request-template-exists

"$schema": "https://raw.githubusercontent.com/todogroup/repolinter/master/rulesets/schema.json"
version: 2
axioms:
  linguist: language
  licensee: license
rules:

  # License related rules
  license-file-exists:
    level: error
    rule:
      type: file-existence
      options:
        globsAny:
        - LICENSE*
        - COPYING*
        nocase: true
    policyUrl: http://go/oss-licensing
  license-detectable-by-licensee:
    level: warning
    where:
    - license=*
    rule:
      type: license-detectable-by-licensee
      options: {}
    policyUrl: http://go/oss-licensing
  source-license-headers-exist:
    level: warning
    rule:
      type: file-starts-with
      options:
        globsAll:
        - "**/*.{c,cc,c++,go,h,java,js,m,py,rb,scala,sh,swift}"
        - "!node_modules/**"
        lineCount: 8
        patterns:
        - Copyright
        - License
        flags: i
    policyUrl: http://go/oss-licensing

# codemeta-file-exists:
#   level: error
#   rule:
#     type: file-existence
#     options:
#       globsAny:
#       - codemeta.json
#       - codemeta.yaml
#       nocase: true

  readme-file-exists:
    level: error
    rule:
      type: file-existence
      options:
        globsAny:
        - README*
        nocase: true
  contributing-file-exists:
    level: error
    rule:
      type: file-existence
      options:
        globsAny:
        - "{docs/,.github/,}CONTRIB*"
        nocase: true

  binaries-not-present:
    level: error
    rule:
      type: file-type-exclusion
      options:
        type:
        - "**/*.exe"
        - "**/*.dll"
        - "!node_modules/**"

  integrates-with-ci:
    level: error
    rule:
      type: file-existence
      options:
        globsAny:
        # currently Twitter really only uses Travis and GitHub Actions
        - ".travis.yml"
        - ".github/workflows/!(repolinter.yml|cla.yml)"

  # make sure all TODOs for newly created projects have been completed and removed
  complete-new-project-todos:
    level: error
    rule:
      type: file-not-contents
      options:
        globsAll:
        - "README.*"
        - "codemeta.*"
        flags: i
        content: TODO\(new project\)
        human-readable-content: TODO(new project)

